spring:
  application:
    name: gateway-service
  jackson:
    serialization:
      indent-output: true
server:
  port: 7000    
  
management:
  endpoint:
    health:
      enabled: true
    beans:
      enabled: true
    shutdown:
      enabled: true  
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka